version: '3.8'
services:
  mongodb:
    restart: always
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - nest-mongodb
    expose:
      - 27017
        
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.backend
    environment: 
      - APP_PORT=8000
      - MONGODB_URL=mongodb://mongodb:27017
    volumes:
      - ./backend/src:/backend/src
    ports:
      - "8000:8000"
    stdin_open: true
    restart: always
    depends_on:
      - mongodb
    networks:
    - nest-mongodb
    - react-nest 
     
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.frontend
    environment: 
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend/src:/frontend/src
    ports:
      - "5173:5173"
    stdin_open: true
    restart: always
    networks:
      - react-nest
    depends_on:
    - backend

networks:
  react-nest:
  nest-mongodb:

volumes:
  mongo_data:
